<?php

return [
    'dashboard' => [
        'name' => trans('Dashboard'),
        'path' => '/admin',
        'icon' => 'dashboard',
        'perms' => [],
        'children' => [],
    ],
    'posts' => [
        'name' => trans('Wpisy'),
        'path' => '#',
        'icon' => 'pencil-square-o',
        'perms' => [],
        'children' => [
            'all_posts' => [
                'name' => trans('Wyświetl wszystkie wpisy'),
                'path' => '/admin/frame/list/post',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'add_post' => [
                'name' => trans('Dodaj nowy wpis'),
                'path' => '/admin/frame/new/post',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'post_taxonomy' => [
                'name' => trans('Wyświetl podziały wpisów'),
                'path' => '/admin/frame/list/post-taxonomy',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
        ],
    ],
    'pages' => [
        'name' => trans('Strony'),
        'path' => '#',
        'icon' => 'files-o',
        'perms' => [],
        'children' => [
            'all_pages' => [
                'name' => trans('Wyświetl wszystkie strony'),
                'path' => '/admin/frame/list/page',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'add_page' => [
                'name' => trans('Dodaj nową stronę'),
                'path' => '/admin/frame/new/page',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
        ],
    ],
    'nav' => [
        'name' => trans('Nawigacja'),
        'path' => '/admin/nav/list',
        'icon' => 'sitemap',
        'perms' => [],
        'children' => [],
    ],
    'products' => [
        'name' => trans('Katalog produktów'),
        'path' => '#',
        'icon' => 'shopping-basket',
        'perms' => [],
        'children' => [
            'all_products' => [
                'name' => trans('Wyświetl wszystkie produkty'),
                'path' => '/admin/frame/list/product',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'product_taxonomy' => [
                'name' => trans('Wyświetl podziały produktów'),
                'path' => '/admin/frame/list/product-taxonomy',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
        ],
    ],
    'widgets' => [
        'name' => trans('Widżety'),
        'path' => '/admin/widget/list',
        'icon' => 'cube',
        'perms' => [],
        'children' => [],
    ],
    'forms' => [
        'name' => trans('Formularze'),
        'path' => '/admin/form/list',
        'icon' => 'envelope-o',
        'perms' => [],
        'badge' => GC\Model\Form\Sent::select()->fields("SUM(status = 'unread') AS unread")->fetch()['unread'],
        'children' => [],
    ],
    'popup' => [
        'name' => trans('Wyskakujące okienka'),
        'path' => '/admin/popup/list',
        'icon' => 'external-link',
        'perms' => [],
        'children' => [],
    ],
    'files' => [
        'name' => trans('Pliki'),
        'path' => '#',
        'icon' => 'folder-open-o',
        'perms' => [],
        'children' => [],
    ],
    'dumps' => [
        'name' => trans('Kopie zapasowe'),
        'path' => '/admin/dump/list',
        'icon' => 'database',
        'perms' => [],
        'children' => [],
    ],
    'staff' => [
        'name' => trans('Pracownicy'),
        'path' => '#',
        'icon' => 'users',
        'perms' => ['manage_staff'],
        'children' => [
            'all_staff' => [
                'name' => trans('Wyświetl pracowników'),
                'path' => '/admin/staff/list',
                'icon' => '',
                'perms' => ['manage_staff'],
                'children' => [],
            ],
            'add_staff' => [
                'name' => trans('Dodaj nowego pracownika'),
                'path' => '/admin/staff/new',
                'icon' => '',
                'perms' => ['manage_staff'],
                'children' => [],
            ],
            'all_staff_groups' => [
                'name' => trans('Wyświetl wszystkie grupy'),
                'path' => '/admin/staff/group/list',
                'icon' => '',
                'perms' => ['manage_staff_groups'],
                'children' => [],
            ],
            'add_staff_group' => [
                'name' => trans('Dodaj nową grupę'),
                'path' => '/admin/staff/group/new',
                'icon' => '',
                'perms' => ['manage_staff_groups'],
                'children' => [],
            ],
        ],
    ],
    'root' => [
        'name' => 'Panel programisty',
        'path' => '#',
        'icon' => 'bug',
        'perms' => ['root'],
        'children' => [
            'phpinfo' => [
                'name' => 'PHPInfo',
                'path' => '/root/phpinfo',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'adminer' => [
                'name' => 'Adminer',
                'path' => '/root/adminer',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'requirements' => [
                'name' => 'Wymagania systemowe',
                'path' => '/root/requirements',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
            'checksum' => [
                'name' => 'Sumy kontrolne plików',
                'path' => '/root/checksum/list',
                'icon' => '',
                'perms' => [],
                'children' => [],
            ],
        ],
    ],
];
